## Title: Mcap 2022 respiration and photosynthesis analysis and plotting  
## Author: Jill Ashey 
## Date created: 20230605

#### This script will analyze and plot photosynthesis and respiration rates for M. capitata larvae from Hawaii 2022 pH and temperature experiment
#### Modified from KW, SG, AH & HP scripts 

## Install packages if you dont already have them in your library
if ("tidyverse" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse') 
if ("car" %in% rownames(installed.packages()) == 'FALSE') install.packages('car') 
if ("lme4" %in% rownames(installed.packages()) == 'FALSE') install.packages('lme4') 
if ("lmerTest" %in% rownames(installed.packages()) == 'FALSE') install.packages('lmerTest') 
if ("scales" %in% rownames(installed.packages()) == 'FALSE') install.packages('scales') 
if ("cowplot" %in% rownames(installed.packages()) == 'FALSE') install.packages('cowplot') 
if ("ggplot2" %in% rownames(installed.packages()) == 'FALSE') install.packages('ggplot2') 
if ("effects" %in% rownames(installed.packages()) == 'FALSE') install.packages('effects') 
if ("emmeans" %in% rownames(installed.packages()) == 'FALSE') install.packages('emmeans') 
if ("multcomp" %in% rownames(installed.packages()) == 'FALSE') install.packages('multcomp') 

#load packages
library("ggplot2")
library("tidyverse")
library('car')
library('lme4')
library('lmerTest')
library('scales')
library('cowplot')
library('effects')
library('emmeans')
library('multcomp')

# Set working directory 
setwd("/Users/jillashey/Desktop/PutnamLab/Repositories/Hawaii2022_pH_Temp_Mcap_Pacu/")

# Load data for P and R rates generated by Respirometry_Extraction.R script
PRdata <- read.csv("output/Respiration/oxygen_P_R_calc_Mcap2022.csv")

# Calculate a gross photosynthesis : respiration (P:R) ratio. This calculation will provide a ratio that will show the amount of oxygen produced compared to consumed, which is an indicator of energy availability. A ratio >1 indicates more photosynthesis than respiration and a ratio <1 indicates less photosynthesis than respiration.   
PRdata$ratio<-abs(PRdata$GP.nmol.org.min)/abs(PRdata$R.nmol.org.min) #calculate ratio with absolute values of gross photosynthesis and respiration

#Examine plot of data to look for outliers.  
plot(PRdata$ratio)

# Remove outliers detected by values of P:R ratio data
PRdata <- PRdata %>%
  filter(ratio < 8)
plot(PRdata$ratio) # outliers are removed - removed about 10 samples 

# Remove any respiration values that were above 0 (respiration is oxygen consumption, so we expect values less than 0 for negative rates)
plot(PRdata$R.nmol.org.min)
PRdata<-PRdata%>%filter(R.nmol.org.min < 0) # now down to 18 samples 

# Remove any respiration values that were outliers
PRdata<-PRdata%>%filter(R.nmol.org.min > -0.15) #Outliers are removed and values are removed where respiration is >0. Respiration is oxygen consumption, so we expect values less than 0 for negative rates.  
plot(PRdata$R.nmol.org.min)



# Plot Respiration data as a boxplot 
r_plot <- ggplot(PRdata, aes(x = Treatment, y = abs(R.nmol.org.min))) +
  geom_boxplot()
r_plot

# Plot Net Photosynthesis data as a boxplot. Net photosynthesis is excess oxygen production after subtracting the oxygen consumed (respiration).   
np_plot <- ggplot(PRdata, aes(x = Treatment, y = P.nmol.org.min)) +
  geom_boxplot()
np_plot

# Plot Gross Photosynthesis data as a boxplot. Gross photosynthesis is net photosynthesis rates plus the oxygen consumed through respiration. 
gp_plot <- ggplot(PRdata, aes(x = Treatment, y = GP.nmol.org.min)) +
  geom_boxplot()
gp_plot





## Analyze data 
### Respiration 
# Build ANOVA model and examine results for analysis of respiration.  
Rmodel1<-aov(R.nmol.org.min~Treatment, data=PRdata)
summary(Rmodel1) # results are not significant 

# Check assumptions of model for residual normality and variance.    
qqPlot(residuals(Rmodel1)) #check normality assumption
leveneTest(residuals(Rmodel1)~Treatment, data=PRdata) #check for homogeneity of variance 
# Data meets normality assumptions and passes homogenity of variance

# Test with non-parametric test 
kruskal.test(R.nmol.org.min~Treatment, data=PRdata) # Results are also not significant

# Conduct post-hoc test - not really necessary here bc no significance in the first place 
emm<-emmeans(Rmodel1, ~Treatment)
cld(emm)


### Net photosynthesis 
# Build ANOVA model and examine results for analysis of net photosynthesis.  
NPmodel1<-aov(P.nmol.org.min~Treatment, data=PRdata)
summary(NPmodel1) # results are not significant 

# Check assumptions of model for residual normality and variance.    
qqPlot(residuals(NPmodel1)) #check normality assumption
leveneTest(residuals(NPmodel1)~Treatment, data=PRdata) #check for homogeneity of variance 
# Data meets normality assumptions and passes homogenity of variance

# Test with non-parametric test 
kruskal.test(P.nmol.org.min~Treatment, data=PRdata) # Results are also not significant

# Conduct post-hoc test - not really necessary here bc no significance in the first place 
emm<-emmeans(NPmodel1, ~Treatment)
cld(emm)


### Gross photosynthesis 
# Build ANOVA model and examine results for analysis of gross photosynthesis.   
GPmodel1<-aov(GP.nmol.org.min~Treatment, data=PRdata)
summary(GPmodel1) # results are not significant 

# Check assumptions of model for residual normality and variance.    
qqPlot(residuals(GPmodel1)) #check normality assumption
leveneTest(residuals(GPmodel1)~Treatment, data=PRdata) #check for homogeneity of variance 
# Data meets normality assumptions and passes homogenity of variance

# Test with non-parametric test 
kruskal.test(GP.nmol.org.min~Treatment, data=PRdata) # Results are also not significant

# Conduct post-hoc test - not really necessary here bc no significance in the first place 
emm<-emmeans(GPmodel1, ~Treatment)
cld(emm)
